# SPDX-License-Identifier: MIT
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - closed

enable-email-notifications: true

jobs:
  cascade:
    runs-on: docker
    container:
      image: 'code.forgejo.org/oci/node:22-bookworm'
    if: >
      ! contains(forge.event.pull_request.title, '[skip cascade]')
    steps:
      - uses: https://code.forgejo.org/actions/cascading-pr@v2.2.0
        with:
          origin-url: ${{ env.FORGEJO_SERVER_URL }}
          origin-repo: forgejo/runner
          origin-token: ${{ secrets.CASCADING_PR_ORIGIN }}
          origin-pr: ${{ forge.event.pull_request.number }}
          destination-url: ${{ env.FORGEJO_SERVER_URL }}
          destination-repo: actions/setup-forgejo
          destination-fork-repo: cascading-pr/setup-forgejo
          destination-branch: main
          destination-token: ${{ secrets.CASCADING_PR_DESTINATION }}
          close-merge: true
          update: .forgejo/cascading-pr-setup-forgejo
