name: goreleaser

on:
  push:
    branches: [ main ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.1'
      - name: goreleaser
        uses: https://github.com/goreleaser/goreleaser-action@v4
        with:
            distribution: goreleaser-pro
            version: latest
            args: release --nightly --skip-publish
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: publish to s3
        run: |
          apt update -y && apt install -y python python3-pip
          pip install awscli
          rm dist/artifacts.json dist/metadata.json dist/config.yaml
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}/act_runner/main/
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
