name: push
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.ref}}
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.23.6
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: go test -cover ./...
      env:
        CGO_ENABLED: 0
        GOFLAGS: -mod=vendor
